<<<<<<< Local Changes
sudo: required
services:
 - docker

before_install:
 -  =======
sudo: required
language: generic
services:
 - docker

before_install:
 - docker build -t justandrewentain/docker-react -f Dockerfile.dev .
<<<<<<< Local Changes
>>>>>>> External Changes
=======

script:
 - docker run justandrewentain/docker-react npm run test -- --coverage>>>>>>> External Changes
